name: Windows Benchmarks

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Add MinGW to PATH
        run: |
          echo "Adding MinGW to PATH"
          echo "C:\\msys64\\mingw64\\bin" >> $env:GITHUB_PATH

      - name: Configure CMake Tests
        run: cmake -S ${{github.workspace}}/BPlotter -B ${{github.workspace}}/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target BPlotterBenchmarks

      - name: Test
        working-directory: ${{github.workspace}}/build/benchmarks/${{matrix.build_type}}
        run: .\BPlotterBenchmarks.exe

